# Generated by Django 5.1.1 on 2024-12-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventmaster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("unregistered", "Unregistered"),
                    ("organizer", "Event Organizer"),
                    ("admin", "Administrator"),
                ],
                default="organizer",
                max_length=50,
            ),
        ),
    ]
