# Generated by Django 5.1.1 on 2024-10-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eventmaster", "0002_subevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subevent", old_name="title", new_name="titles",
        ),
    ]
